# Generated by Django 6.0.2 on 2026-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_city_if_missing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=100,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
