# Generated by Django 6.0.2 on 2026-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счёт"),
                    ("card", "Банковская карта (Stripe)"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
