# Generated by Django 6.0.2 on 2026-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/image", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/image", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
