# Generated by Django 6.0.2

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                help_text="Обновляется при изменении курса или его уроков",
                verbose_name="Дата последнего обновления",
            ),
            preserve_default=False,
        ),
    ]
